volumes:
  scowldb:
services:
  database:
    image: "postgres:alpine"
    env_file: 
      - .env
    ports: 
      - 5532:5432
    volumes:
      - scowldb:/opt/scowl
  scowlapi:
    image: "fuzzylemma/scowldb:latest"
    ports: 
      - 8888:8888
